version: "3"
services:
  aprsd:
    image: hemna6969/aprsd:latest
    container_name: aprsd
    volumes:
        - /opt/docker/aprsd/config:/config
        - /opt/docker/aprsd/plugins:/plugins
    restart: unless-stopped
    environment:
        - TZ=America/New_York
        - APRS_PLUGINS=aprsd-slack-plugin>=1.0.2
